name: Documentation
description: Report missing, unclear, or incorrect documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Unclear/confusing documentation
        - Incorrect/outdated documentation
        - Typo/grammar issue
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue located?
      placeholder: |
        - README.md section "Getting Started"
        - Settings page tooltip for "Model selection"
        - Error message when ONNX Runtime fails
        - etc.
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What's Wrong?
      description: Describe the documentation issue
      placeholder: The current documentation says... but it should say...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        The documentation should explain...
        Or provide an example of...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or information
      placeholder: Screenshots, related issues, etc.
